# Generated by Django 2.1.3 on 2018-11-15 13:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("photo", models.ImageField(upload_to="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("email_sent_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
