# Generated by Django 5.1.3 on 2024-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photobooth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="photo_with_bg",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
